name: Trigger on Release 

on:
  create:
    tags:
      - v*

jobs:
  release:
    name: releasing latest tag to ubuntu 
    runs-on: ubuntu-latest
    steps:
      - name: check some system info
        run: |
          echo Current Working Directory, processes, disk free
          pwd
          ps -ef
          df -h
          
      - name: check out codes
        uses: actions/checkout@v2
      
      - name: Validate Go releaser configuration
        uses: docker://goreleaser/goreleaser:latest
        with:
          arg: check
          
      - name: check status
        if: ${{ success() }}
        run: echo check successful
        
      - name: check status
        if: ${{ failure() }}
        run: echo check failed
          
      - name: release codes
        uses: docker://goreleaser/goreleaser:latest
        with:
          arg: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: check status
        if: ${{ success() }}
        run: echo release successful
        
      - name: check status
        if: ${{ failure() }}
        run: echo release failed
          
      - name: report completion
        if: ${{ always() }}
        run: echo End of scripts
        
