name: CI step for go

on: 
   push:
     branches: [main, master]
     
     
jobs:
  my-job: 
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      run: |
         echo Hi there!
         ls
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
         # The Go version to download (if necessary) and use. Supports semver spec and ranges.
         go-version: 1.12
    - name: Check Go version
      run: |
           go version
           ls
    - name: checkout new codes
      uses: actions/checkout@v2
    - name: list files
      run: |
         ls
         cat calc.go
         
    - name: CHECKOUT PRIVATE REPO
      uses: actions/checkout@v2
      with:
        repository: lowkh2/GoSchoolRemoteExample
        path: remoteRepo
        token: ${{ secrets.GO_REMOTE }}
        
    - name: check files
      run: |
         ls
         pwd
         cd remoteRepo
         ls
         cat myText.txt
         cd ..

    - name: Install dependencies
      run: |
         go get github.com/franela/goblin
