name: CI setp for go

on: 
   push:
     branches: [main, master]
     
     
jobs:
  my-job: 
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      run: |
         echo Hi there!
         
